"use strict";
const copy = {
  en: {skip:"Skip to content",navStories:"Our stories",navAbout:"About GeeDrama",navApp:"The app",heroEyebrow:"Small screen. Big feelings.",heroLine1:"A little time.",heroLine2:"A whole lot of",heroLine3:"drama.",heroDescription:"A secret revealed. A choice that changes everything. Meet the stories that make you want one more episode.",explore:"Explore the stories",heroNote:"Short episodes. Stories that stay with you.",heroCaption:"The GeeDrama collection",heroGenres:"Romance / Revenge / Fantasy",strip1:"Love. Secrets. Second chances.",strip2:"Find your next story.",collection:"The collection",storiesTitle:"Seven stories. So much to feel.",storiesDescription:"From city lights to moonlit kingdoms, discover a world worth getting lost in.",romanceRevenge:"Romance · Revenge",romanceSecrets:"Romance · Secrets",fantasyRomance:"Fantasy · Romance",fantasy:"Fantasy",dramaRevenge:"Drama · Revenge",aboutEyebrow:"Made for your everyday",aboutTitle:"A small break. A different world.",aboutIntro:"GeeDrama turns your spare moments into stories worth following. Get caught up in the characters, the choices, and the twist you never saw coming.",about1Title:"Get straight to the story",about1Copy:"Short episodes keep the story moving, with a little room for drama in your day.",about2Title:"Feel every turn",about2Copy:"Root for a character. Question a motive. Stay to find out what happens next.",appEyebrow:"Meet GeeDrama",appTitle:"Your next story goes with you.",appCopy:"Discover short drama series on your phone. Some content requires payment; purchase options and prices are shown in the app.",browse:"Browse the collection",privacy:"Privacy Policy",terms:"Terms of Use",deletion:"Account & data deletion",support:"Contact us",rights:"All rights reserved.",footerNote:"Short episodes. Big emotions.",getIt:"Get it on",androidDownload:"Download for Android",iosDownload:"Download for iOS",iosSoon:"Download link coming soon"},
  zh: {skip:"跳转至正文",navStories:"精选剧集",navAbout:"关于 GeeDrama",navApp:"获取应用",heroEyebrow:"小屏幕，大情绪。",heroLine1:"片刻闲暇，",heroLine2:"走进另一段",heroLine3:"人生。",heroDescription:"一个秘密被揭开，一个决定改变一切。在 GeeDrama，找到让你想再看一集的故事。",explore:"探索精彩剧集",heroNote:"短小的篇幅，留在心里的故事。",heroCaption:"GeeDrama 精选剧集",heroGenres:"爱情 / 复仇 / 奇幻",strip1:"爱情、秘密，与重新开始的机会。",strip2:"找到你的下一个故事。",collection:"精选片单",storiesTitle:"七段故事，万千情绪。",storiesDescription:"从繁华都市到月下王国，走进让你沉浸其中的剧情世界。",romanceRevenge:"爱情 · 复仇",romanceSecrets:"爱情 · 秘密",fantasyRomance:"奇幻 · 爱情",fantasy:"奇幻",dramaRevenge:"剧情 · 复仇",aboutEyebrow:"融入日常的追剧时光",aboutTitle:"歇一会儿，走进另一个世界。",aboutIntro:"GeeDrama 让片刻闲暇变成值得追下去的故事。跟随角色的抉择，感受情绪起伏，期待意想不到的剧情反转。",about1Title:"迅速进入剧情",about1Copy:"短小的剧集，让故事步步推进，也让日常空档多一点精彩。",about2Title:"感受每一次转折",about2Copy:"为角色加油，猜测人物动机，继续追看接下来的故事。",appEyebrow:"认识 GeeDrama",appTitle:"把下一个故事带在身边。",appCopy:"在手机上发现精彩短剧。部分内容需要付费，购买方式与价格请查看应用内说明。",browse:"浏览精选片单",privacy:"隐私政策",terms:"使用条款",deletion:"账号与数据删除",support:"联系我们",rights:"保留所有权利。",footerNote:"短剧集，大情绪。",getIt:"下载自",androidDownload:"下载 Android 版",iosDownload:"下载 iOS 版",iosSoon:"下载链接即将开放"}
};
function changeLanguage(language){
  const lang=language==="zh"?"zh":"en";
  document.documentElement.lang=lang==="zh"?"zh-CN":"en";
  document.title=lang==="zh"?"GeeDrama — 精彩短剧":"GeeDrama — Short Drama Series";
  document.querySelectorAll("[data-i18n]").forEach(node=>{const value=copy[lang][node.dataset.i18n];if(value!==undefined)node.textContent=value;});
  document.querySelectorAll("[data-lang]").forEach(button=>button.setAttribute("aria-pressed",String(button.dataset.lang===lang)));
  const description=document.querySelector('meta[name="description"]');
  if(description)description.content=lang==="zh"?"在 GeeDrama 发现精彩短剧。爱情、复仇与奇幻故事，用短小剧集带来丰富情感。":"Discover GeeDrama short drama series. Romance, revenge and fantasy stories, with big emotions in short episodes.";
  try{localStorage.setItem("geedrama-language",lang);}catch{}
}
document.querySelectorAll("[data-lang]").forEach(button=>button.addEventListener("click",()=>changeLanguage(button.dataset.lang)));
let preferred="en";
try{preferred=localStorage.getItem("geedrama-language")||((navigator.language||"en").toLowerCase().startsWith("zh")?"zh":"en");}catch{}
changeLanguage(preferred);
